# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

 target 'Swifty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'SwiftyJSON', '~> 4.2'
  use_frameworks!

  # Pods for Swifty

  target 'SwiftyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
